steps:
    - name: 'gcr.io/cloud-builders/docker'
      dir:  'containers/train'   # remove-for-manual
      args: [ 'build', '-t', 'gcr.io/taxi-mlops-demo/mlops-demo-train:latest', '.' ]
images:
    - 'gcr.io/taxi-mlops-demo/mlops-demo-train:latest'
